export const customerList = [
    {
        id: 1,
        name: "Visalini",
        title: "CTO",
        company: "NexusFlow Solutions",
        email: "visalini@nexusflow.com",
        mobilePhone: "+91 98765 43210",
        workPhone: "044 2345 6789",
        socialHandle: "@visalini_dev",
        status: "Active",
        avatar: "https://i.pravatar.cc/150?u=visalini",
        lastContacted: "2 days ago"
    },
    {
        id: 2,
        name: "Sriraja",
        title: "Product Manager",
        company: "Innovate AI",
        email: "sriraja@innovate.ai",
        mobilePhone: "+91 87654 32109",
        workPhone: "044 3456 7890",
        socialHandle: "@sriraja_pm",
        status: "Active",
        avatar: "https://i.pravatar.cc/150?u=sriraja",
        lastContacted: "5 hours ago"
    },
    {
        id: 3,
        name: "Ragul",
        title: "Chief Architect",
        company: "Pied Piper Systems",
        email: "ragul@piedpiper.systems",
        mobilePhone: "+91 76543 21098",
        workPhone: "044 4567 8901",
        socialHandle: "@ragul_arch",
        status: "Lead",
        avatar: "https://i.pravatar.cc/150?u=ragul",
        lastContacted: "1 week ago"
    },
    {
        id: 4,
        name: "Gopika",
        title: "Head of Support",
        company: "ZenDesk Clone Inc.",
        email: "gopika@zdesk.com",
        mobilePhone: "+91 65432 10987",
        workPhone: "044 5678 9012",
        socialHandle: "@gopika_support",
        status: "Active",
        avatar: "https://i.pravatar.cc/150?u=gopika",
        lastContacted: "Just now"
    },
    {
        id: 5,
        name: "Sudar",
        title: "HR Director",
        company: "Global Systems",
        email: "sudar@global.systems",
        mobilePhone: "+91 54321 09876",
        workPhone: "044 6789 0123",
        socialHandle: "@sudar_hr",
        status: "Inactive",
        avatar: "https://i.pravatar.cc/150?u=sudar",
        lastContacted: "1 month ago"
    },
    {
        id: 6,
        name: "Hari",
        title: "Sales Lead",
        company: "TechNova",
        email: "hari@technova.com",
        mobilePhone: "+91 43210 98765",
        workPhone: "044 7890 1234",
        socialHandle: "@hari_sales",
        status: "Lead",
        avatar: "https://i.pravatar.cc/150?u=hari",
        lastContacted: "Yesterday"
    },
    {
        id: 7,
        name: "Vivek",
        title: "CEO",
        company: "Freshworks Solutions",
        email: "vivek@freshworks.co",
        mobilePhone: "+1 234 567 8901",
        workPhone: "+1 987 654 3210",
        socialHandle: "@vivek_ceo",
        status: "Active",
        avatar: "https://i.pravatar.cc/150?u=vivek",
        lastContacted: "3 days ago"
    }
];
