export const agentList = [
    { id: 1, name: 'Vivek', avatar: 'https://i.pravatar.cc/150?u=vivek' },
    { id: 2, name: 'Sriraja', avatar: 'https://i.pravatar.cc/150?u=sriraja' },
    { id: 3, name: 'Ragul', avatar: 'https://i.pravatar.cc/150?u=ragul' },
    { id: 4, name: 'Visalini', avatar: 'https://i.pravatar.cc/150?u=visalini' },
    { id: 5, name: 'Gopika', avatar: 'https://i.pravatar.cc/150?u=gopika' },
    { id: 6, name: 'Sudar', avatar: 'https://i.pravatar.cc/150?u=sudar' },
    { id: 7, name: 'Hari', avatar: 'https://i.pravatar.cc/150?u=hari' },
];

export const ticketList = [
    {
        id: 1024,
        subject: 'Issues with analytics dashboard reports',
        status: 'Open',
        priority: 'Low',
        agent: 'Sudar',
        requester: 'Ragul',
        company: 'Freshworks',
        responseTime: '19 days ago',
        resolutionInfo: 'Resolution overdue by 13 days',
        overdue: true,
        date: '2024-03-01',
        avatar: 'https://i.pravatar.cc/150?u=ragul',
    },
    {
        id: 1023,
        subject: 'Unable to login via SSO after update',
        status: 'Closed',
        priority: 'Medium',
        agent: 'Vivek',
        requester: 'Hari',
        company: 'Acme Corp',
        responseTime: '1 day ago',
        resolutionInfo: 'Resolution overdue by 13 days',
        overdue: true,
        date: '2024-03-10',
        avatar: 'https://i.pravatar.cc/150?u=hari',
    },
    {
        id: 1022,
        subject: 'Billing inquiry regarding Q3 invoice',
        status: 'Closed',
        priority: 'Medium',
        agent: 'Sriraja',
        requester: 'Visalini',
        company: 'Pied Piper',
        responseTime: '1 day ago',
        resolutionInfo: 'Resolved',
        overdue: false,
        date: '2024-03-12',
        avatar: 'https://i.pravatar.cc/150?u=visalini',
    },
    {
        id: 1021,
        subject: 'API integration documentation missing endpoints',
        status: 'Open',
        priority: 'High',
        agent: 'Gopika',
        requester: 'Sriraja',
        company: 'Mystic Falls Tech',
        responseTime: '2 hours ago',
        resolutionInfo: 'Resolution due in 4 hours',
        overdue: false,
        date: '2024-03-15',
        avatar: 'https://i.pravatar.cc/150?u=sriraja2',
    },
    {
        id: 1020,
        subject: 'Critical: Production server downtime',
        status: 'Open',
        priority: 'Urgent',
        agent: null,
        requester: 'Ragul',
        company: 'Global Systems',
        responseTime: '15 mins ago',
        resolutionInfo: 'Resolution overdue by 30 mins',
        overdue: true,
        date: '2024-03-16',
        avatar: 'https://i.pravatar.cc/150?u=ragul2',
    },
    {
        id: 1019,
        subject: 'Feature request: Export to PDF option',
        status: 'Assigned',
        priority: 'Low',
        agent: 'Hari',
        requester: 'Gopika',
        company: 'TechNova',
        responseTime: '3 days ago',
        resolutionInfo: 'Within SLA',
        overdue: false,
        date: '2024-03-13',
        avatar: 'https://i.pravatar.cc/150?u=gopika2',
    },
    {
        id: 1018,
        subject: 'Password reset email not being received',
        status: 'Assigned',
        priority: 'High',
        agent: 'Ragul',
        requester: 'Sudar',
        company: 'StartupXYZ',
        responseTime: '5 hours ago',
        resolutionInfo: 'Resolution due in 2 hours',
        overdue: false,
        date: '2024-03-14',
        avatar: 'https://i.pravatar.cc/150?u=sudar2',
    },
];